spring:
  application:
    name: task-service
  datasource:
    url: jdbc:postgresql://localhost:5432/taskdb
    username: postgres
    password: 0205
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8081
jwt:
  secret:
  expiration: 86400000
user-service:
  url: http://localhost:8082/api/users
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics